### ISSUE TITLE
location of the embeddings 

### ISSUE THREAD

**Issue by happy15** [simonw/llm-clip#4]
Hey, very interesting plugin for llm and love it.

Just curious, where is the embeddings stored in file system?

**Comment by saket424** [comment]
@happy15 
On my Mac, I see some of the llm data artifacts are stored in

ls /Users/username/Library/Application Support/io.datasette.llm
aliases.json		gguf				llm_embed_onnx			logs.db				sentence-transformers.json

The other embedding model artifacts  are stored in the usual hugging face hub
ls ~/.cache/huggingface/hub 
models--sentence-transformers--clip-ViT-B-32
models--TaylorAI--bge-micro-v2
models--sentence-transformers--clip-ViT-L-14
models--google--siglip-so400m-patch14-384
models--sentence-transformers--all-MiniLM-L12-v2
models--sentence-transformers--multi-qa-MiniLM-L6-cos-v1
models--sentence-transformers--all-MiniLM-L6-v2
models--vikhyatk--moondream2
models--microsoft--Florence-2-large
models--sentence-transformers--all-mpnet-base-v2
version.txt

**Comment by happy15** [comment]
> @happy15 On my Mac, I see some of the llm data artifacts are stored in
> 
> ls /Users/username/Library/Application Support/io.datasette.llm aliases.json gguf llm_embed_onnx logs.db sentence-transformers.json
> 
> The other embedding model artifacts are stored in the usual hugging face hub ls ~/.cache/huggingface/hub models--sentence-transformers--clip-ViT-B-32 models--TaylorAI--bge-micro-v2 models--sentence-transformers--clip-ViT-L-14 models--google--siglip-so400m-patch14-384 models--sentence-transformers--all-MiniLM-L12-v2 models--sentence-transformers--multi-qa-MiniLM-L6-cos-v1 models--sentence-transformers--all-MiniLM-L6-v2 models--vikhyatk--moondream2 models--microsoft--Florence-2-large models--sentence-transformers--all-mpnet-base-v2 version.txt

thanks for pointing that out.
